<?php
/**
 * SUMOHeavy_GlobalMessage
 *
 * @category   SUMOHeavy
 * @package    SUMOHeavy_GlobalMessage
 * @copyright  Copyright 2013 SUMO Heavy Industries, LLC
 * @author     Sean Kennedy <support@sumoheavy.com>
 */
$_helper = $this->helper('cms');
$_enabled = Mage::getStoreConfig(
    'sumoheavy_globalmessage/globalmessage/enabled',
    Mage::app()->getStore()
);
$_message = Mage::getStoreConfig(
    'sumoheavy_globalmessage/globalmessage/message',
    Mage::app()->getStore()
);
?>

<?php if ($_enabled): ?>
<div class="sh-globalmessage">
    <?php
    echo $_helper->getBlockTemplateProcessor()
        ->filter($_message);
    ?>
</div>
<?php endif; ?>
